version: '3.8'
services:
  api:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
      - 5678:5678
    volumes:
      - ./:/flask-api
    depends_on:
      - database
    env_file: .env
    restart: always
  database:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - ./initdb/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: framework_challenge

